name: maydon_app
description: Maydon application

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  firebase_database: ^10.2.7
  firebase_storage: ^11.2.8
  firebase_messaging: ^14.6.9
  firebase_remote_config: ^4.2.7
  firebase_analytics: ^10.5.1
  shared_preferences: ^2.2.1
  google_maps_flutter: ^2.5.0
  connectivity_plus: ^5.0.0
  geolocator: ^10.1.0
  firebase_core_web: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/app/
    - assets/images/stadium/
  #   - images/a_dot_ham.jpeg

  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

