// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_LV7uZccrrSdadu6tUgKpp9-36XL3EZw',
    appId: '1:513609381550:web:7d5aaf41dda82595f79f3f',
    messagingSenderId: '513609381550',
    projectId: 'instagram-ui-pdp',
    authDomain: 'instagram-ui-pdp.firebaseapp.com',
    databaseURL: 'https://instagram-ui-pdp-default-rtdb.firebaseio.com',
    storageBucket: 'instagram-ui-pdp.appspot.com',
    measurementId: 'G-GMTTBFB88W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBizzDOO3CyzgzV07m_opavaWRzdzMfyME',
    appId: '1:513609381550:android:9ba294ea67bfc6aff79f3f',
    messagingSenderId: '513609381550',
    projectId: 'instagram-ui-pdp',
    databaseURL: 'https://instagram-ui-pdp-default-rtdb.firebaseio.com',
    storageBucket: 'instagram-ui-pdp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV1H3a57P8DxjykSq9Om4tMg0y8rN1JEs',
    appId: '1:513609381550:ios:1de723008fbc49ddf79f3f',
    messagingSenderId: '513609381550',
    projectId: 'instagram-ui-pdp',
    databaseURL: 'https://instagram-ui-pdp-default-rtdb.firebaseio.com',
    storageBucket: 'instagram-ui-pdp.appspot.com',
    iosBundleId: 'com.pdp.maydonApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV1H3a57P8DxjykSq9Om4tMg0y8rN1JEs',
    appId: '1:513609381550:ios:880661896335eeaaf79f3f',
    messagingSenderId: '513609381550',
    projectId: 'instagram-ui-pdp',
    databaseURL: 'https://instagram-ui-pdp-default-rtdb.firebaseio.com',
    storageBucket: 'instagram-ui-pdp.appspot.com',
    iosBundleId: 'com.pdp.maydonApp.RunnerTests',
  );
}
